name: Check Main PR Source

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is dev
        if: github.head_ref != 'dev'
        run: |
          echo "Error: Pull requests to main must come from the dev branch"
          exit 1
      - name: Source branch is dev
        if: github.head_ref == 'dev'
        run: |
          echo "Source branch is dev, proceeding with checks"
