name: Dev PR Preview Workflow

on:
  pull_request:
    branches: [dev]
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cache key prefix
        id: vars
        run: echo "CACHE_KEY_PREFIX=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.CACHE_KEY_PREFIX }}
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build react-app
        run: yarn build:react-app
        env:
          CI: true
          PUBLIC_URL: /pr-preview/pr-${{ github.event.number }}

      - name: List build directory contents
        run: ls -la examples/react-app/build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./examples/react-app/build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: deploy
