name: Pull Request Checks

on:
  pull_request:
    branches: [dev, main]

jobs:
  conventional-commits-check:
    name: Conventional Commits Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1.1.0

  pr-source-check:
    name: PR Source Check
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    steps:
      - name: Check if source branch is dev
        if: github.head_ref != 'dev'
        run: |
          echo "Error: Pull requests to main must come from the dev branch"
          exit 1
      - name: Source branch is dev
        if: github.head_ref == 'dev'
        run: |
          echo "Source branch is dev, proceeding with checks"
